import { describe, expect, it } from 'vitest';
import { REAGENT_BY_ID, REAGENT_BY_NAME } from './data/reagents';
import { TOOL_BY_ID } from './data/tools';
import { ENCOUNTERS } from './data/encounters';
import type { EngineInventoryItem } from './gameplay';
import type { PatientState } from './state';
import type { CanonicalToolState } from './toolEngine';
import {
  FORAGING_ENCOUNTER_IDS,
  MEEK_ENCOUNTER_IDS,
  TRAPPED_ENCOUNTER_IDS,
  canonicalEncounterPartCandidates,
  deliverEncounterPayload,
  recordSainDeClawsMatch,
  resolveAlluringOdours,
  resolveAntHeist,
  resolveFabledBehemoth,
  resolveFinalRestingPlace,
  resolveFowlFare,
  resolveFriendInNeed,
  resolveLifeSavingTransplant,
  resolveLockAndKey,
  resolveLogKnocking,
  resolveMeekShallInherit,
  resolveMycophiliacs,
  applyMycophiliacsMushroomRarity,
  clearMycophiliacsLocationConditions,
  consumeMycophiliacsMushroomBarter,
  resolveOdoakMarket,
  resolveProjectLaunch,
  resolveRightPlaceWrongTime,
  resolveRiverSnatchers,
  resolveStickEmUp,
  resolveTheBranded,
  resolveTrapped,
  resolveWhatRemains,
  returnSainDeClawsPresents,
  settleSainDeClawsAtSeasonEnd,
  startSainDeClawsQuest,
  type EncounterInventoryItem,
  type ForagingEncounterTransactionState
} from './foragingEncounterTransactions';

const patient = (): PatientState => ({
  id: 'patient-1',
  name: 'Moss',
  species: 'Badger',
  status: 'active',
  ailments: [{
    id: 'ailment-instance-1', ailmentId: 'ailment-1', severity: 'lesser', timerIds: ['timer-1', 'timer-2'],
    conditionIds: [], treatmentHistoryIds: [], status: 'active', instance: 1, repeatIndex: 0,
    specialState: {}, successResolved: false, failureResolved: false, consequenceResolved: false, effectIds: []
  }],
  timers: [
    { id: 'timer-1', ailmentInstanceId: 'ailment-instance-1', current: 6, maximum: 8, status: 'active' },
    { id: 'timer-2', ailmentInstanceId: 'ailment-instance-1', current: 2, maximum: 8, status: 'active' }
  ],
  conditions: [], treatmentHistory: [], journalEvents: []
});

const state = (overrides: Partial<ForagingEncounterTransactionState> = {}): ForagingEncounterTransactionState => ({
  revision: 3,
  reputation: 15,
  trinkets: 4,
  foragingPoints: 2,
  inventory: [],
  patient: patient(),
  tools: [],
  companions: [],
  conditions: [],
  deliveries: [],
  sainDeClawsQuests: [],
  appliedTransactionIds: [],
  ...overrides
});

const canonicalTool = (toolId: string, id = `tool:${toolId}`, quantity = 1): { item: EncounterInventoryItem; tool: CanonicalToolState } => {
  const definition = TOOL_BY_ID.get(toolId)!;
  return {
    item: { id, name: definition.canonicalName, type: 'tool', weight: definition.weight, quantity, canonicalToolId: toolId },
    tool: { instanceId: id, toolId, upgradeId: null, charges: null, broken: false, consumed: false, acquiredBy: 'test', appliedEffectIds: [] }
  };
};

const part = (name: string, partName?: string) => {
  const reagent = REAGENT_BY_NAME.get(name)!;
  const preparation = partName ? reagent.preparations.find(row => row.name === partName)! : reagent.preparations[0];
  return { reagentId: reagent.id, preparationId: preparation.id, reagent, preparation };
};

const inventoryPart = (id: string, name: string, partName?: string, quantity = 1): EncounterInventoryItem => {
  const selected = part(name, partName);
  return {
    id,
    name: `${selected.reagent.canonicalName} (${selected.preparation.name})`,
    type: 'reagent',
    weight: selected.preparation.weight,
    quantity,
    canonicalReagentId: selected.reagentId,
    preparationId: selected.preparationId,
    usesRemaining: selected.preparation.uses,
    ruinedWhenSoaked: true
  };
};

describe('foraging encounter transactions', () => {
  it('targets only canonical encounter IDs generated by the current tables', () => {
    const canonicalIds = new Set(ENCOUNTERS.map(encounter => encounter.id));
    expect(Object.values(FORAGING_ENCOUNTER_IDS).filter(id => !canonicalIds.has(id))).toEqual([]);
    expect(TRAPPED_ENCOUNTER_IDS.filter(id => !canonicalIds.has(id))).toEqual([]);
    expect(MEEK_ENCOUNTER_IDS.filter(id => !canonicalIds.has(id))).toEqual([]);
  });

  it('rejects stale state and duplicate transaction IDs before applying effects', () => {
    const stale = resolveRightPlaceWrongTime({
      transactionId: 'right-place:1', encounterId: FORAGING_ENCOUNTER_IDS.rightPlaceWrongTime,
      expectedRevision: 2, state: state(), choice: 'vigilante',
      playerCard: { value: 8, suit: '♥' }, robberCard: { value: 3, suit: '♠' }
    });
    expect(stale).toMatchObject({ status: 'invalid', code: 'stale-state' });

    const replay = resolveRightPlaceWrongTime({
      transactionId: 'right-place:1', encounterId: FORAGING_ENCOUNTER_IDS.rightPlaceWrongTime,
      expectedRevision: 3, state: state({ appliedTransactionIds: ['right-place:1'] }), choice: 'vigilante',
      playerCard: { value: 8, suit: '♥' }, robberCard: { value: 3, suit: '♠' }
    });
    expect(replay).toMatchObject({ status: 'invalid', code: 'already-applied' });
  });

  it('resolves p.155 branches without inventing a tie result and consumes Archer Bolt', () => {
    const crossbow = canonicalTool('crossbow');
    const bolts = canonicalTool('bolts', 'tool:bolts', 2);
    const archer = resolveRightPlaceWrongTime({
      transactionId: 'right-place:archer', encounterId: FORAGING_ENCOUNTER_IDS.rightPlaceWrongTime,
      expectedRevision: 3, state: state({ inventory: [crossbow.item, bolts.item], tools: [crossbow.tool, bolts.tool] }), choice: 'archer'
    });
    expect(archer.status).toBe('resolved');
    expect(archer.value?.nextState.reputation).toBe(18);
    expect(archer.value?.nextState.inventory.find(row => row.id === bolts.item.id)?.quantity).toBe(1);

    const wounded = resolveRightPlaceWrongTime({
      transactionId: 'right-place:wounded', encounterId: FORAGING_ENCOUNTER_IDS.rightPlaceWrongTime,
      expectedRevision: 3, state: state(), choice: 'vigilante',
      playerCard: { value: 3, suit: '♥' }, robberCard: { value: 8, suit: '♠' }
    });
    expect(wounded.value?.nextState.reputation).toBe(18);
    expect(wounded.value?.directives).toContainEqual({ kind: 'move-to-nearest-settlement-and-abandon-journey', sourcePage: 155 });

    const tie = resolveRightPlaceWrongTime({
      transactionId: 'right-place:tie', encounterId: FORAGING_ENCOUNTER_IDS.rightPlaceWrongTime,
      expectedRevision: 3, state: state(), choice: 'vigilante',
      playerCard: { value: 8, suit: '♥' }, robberCard: { value: 8, suit: '♠' }
    });
    expect(tie).toMatchObject({ status: 'invalid', code: 'ambiguous-tie' });
  });

  it('enforces p.161 exact Forest rarity and decreases only the selected Ailment Timer', () => {
    const eligible = canonicalEncounterPartCandidates({ region: 'Forest', exactRarity: 5 })[0];
    const success = resolveFriendInNeed({
      transactionId: 'friend:1', encounterId: FORAGING_ENCOUNTER_IDS.friendInNeed, expectedRevision: 3,
      state: state(), choice: 'help', card: { value: 5, suit: '♦' }, ...eligible, timerId: 'timer-1'
    });
    expect(success.status).toBe('resolved');
    expect(success.value?.nextState.patient?.timers.map(row => row.current)).toEqual([5, 2]);
    expect(success.value?.nextState.inventory).toHaveLength(1);

    const forged = resolveFriendInNeed({
      transactionId: 'friend:2', encounterId: FORAGING_ENCOUNTER_IDS.friendInNeed, expectedRevision: 3,
      state: state(), choice: 'help', card: { value: 6, suit: '♦' }, ...eligible, timerId: 'timer-1'
    });
    expect(forged).toMatchObject({ status: 'invalid', code: 'invalid-selection' });
  });

  it('treats p.161 all Parts as physical parts, not duplicate preparation variants', () => {
    const beetles = REAGENT_BY_NAME.get('Beetles')!;
    const oneShell = beetles.preparations[0];
    const success = resolveLogKnocking({
      transactionId: 'log:1', encounterId: 'foraging-forest-6', expectedRevision: 3, state: state(),
      reagentId: beetles.id, partSelections: [{ preparationId: oneShell.id }]
    });
    expect(success.value?.nextState.inventory).toHaveLength(1);

    const duplicated = resolveLogKnocking({
      transactionId: 'log:2', encounterId: 'foraging-forest-6', expectedRevision: 3, state: state(),
      reagentId: beetles.id, partSelections: beetles.preparations.map(row => ({ preparationId: row.id }))
    });
    expect(duplicated).toMatchObject({ status: 'invalid', code: 'invalid-selection' });
  });

  it('applies p.162 all-Timer cost once and validates the Forest FAIR reward', () => {
    const fair = canonicalEncounterPartCandidates({ region: 'Forest', requiredTag: 'FAIR' })[0];
    const success = resolveAlluringOdours({
      transactionId: 'odours:1', encounterId: FORAGING_ENCOUNTER_IDS.alluringOdours, expectedRevision: 3,
      state: state(), card: { value: 7, suit: '♣' }, ...fair
    });
    expect(success.value?.nextState.patient?.timers.map(row => row.current)).toEqual([5, 1]);
    expect(success.value?.nextState.inventory).toHaveLength(1);

    const low = resolveAlluringOdours({
      transactionId: 'odours:2', encounterId: FORAGING_ENCOUNTER_IDS.alluringOdours, expectedRevision: 3,
      state: state(), card: { value: 6, suit: '♥' }
    });
    expect(low.value?.nextState.inventory).toHaveLength(0);
  });

  it('keeps p.162 Branded branches exclusive and sends Compassion to canonical Lesser Ailment creation', () => {
    const compassion = resolveTheBranded({
      transactionId: 'branded:1', encounterId: FORAGING_ENCOUNTER_IDS.theBranded, expectedRevision: 3,
      state: state(), choice: 'compassion'
    });
    expect(compassion.value?.nextState.reputation).toBe(15);
    expect(compassion.value?.directives).toContainEqual({ kind: 'start-lesser-ailment-before-overstay', sourcePage: 162 });
    const duty = resolveTheBranded({
      transactionId: 'branded:2', encounterId: FORAGING_ENCOUNTER_IDS.theBranded, expectedRevision: 3,
      state: state(), choice: 'duty'
    });
    expect(duty.value?.nextState.reputation).toBe(16);
    expect(duty.value?.directives).toEqual([]);
  });

  it('uses an exact unit snapshot for p.168 card-indexed loss and soaks retrieved Reagents', () => {
    const reagent = inventoryPart('part:1', 'Beech', undefined, 2);
    const keepsake: EncounterInventoryItem = { id: 'keepsake', name: 'Keepsake', type: 'item', weight: 1 };
    const bag = [reagent, keepsake];
    const soaked = resolveRiverSnatchers({
      transactionId: 'river:1', encounterId: FORAGING_ENCOUNTER_IDS.riverSnatchers, expectedRevision: 3,
      state: state({ inventory: bag }), card: { value: 1, suit: '♥' }, expectedBagUnitIds: ['part:1', 'part:1', 'keepsake'], selectedItemId: 'part:1'
    });
    expect(soaked.value?.nextState.inventory.find(row => row.id === 'part:1')?.quantity).toBe(1);

    const retrieved = resolveRiverSnatchers({
      transactionId: 'river:2', encounterId: FORAGING_ENCOUNTER_IDS.riverSnatchers, expectedRevision: 3,
      state: state({ inventory: bag }), card: { value: 3, suit: '♦' }, expectedBagUnitIds: ['part:1', 'part:1', 'keepsake'], selectedItemId: 'keepsake'
    });
    expect(retrieved.value?.nextState.inventory).toHaveLength(2);

    const stale = resolveRiverSnatchers({
      transactionId: 'river:3', encounterId: FORAGING_ENCOUNTER_IDS.riverSnatchers, expectedRevision: 3,
      state: state({ inventory: bag }), card: { value: 1, suit: '♠' }, expectedBagUnitIds: ['keepsake', 'part:1', 'part:1'], selectedItemId: 'keepsake'
    });
    expect(stale).toMatchObject({ status: 'invalid', code: 'stale-state' });
  });

  it('makes every p.170 Row leave and only Spades lose a Reagent; Face consumes a Bolt', () => {
    const row = resolveFabledBehemoth({
      transactionId: 'goliath:row', encounterId: FORAGING_ENCOUNTER_IDS.fabledBehemoth, expectedRevision: 3,
      state: state(), choice: 'row', card: { value: 4, suit: '♥' }
    });
    expect(row.value?.directives).toContainEqual({ kind: 'leave-current-location', sourcePage: 170 });

    const crossbow = canonicalTool('crossbow');
    const bolt = canonicalTool('bolts');
    const titan = canonicalEncounterPartCandidates({ types: ['TITAN'] })[0];
    const face = resolveFabledBehemoth({
      transactionId: 'goliath:face', encounterId: FORAGING_ENCOUNTER_IDS.fabledBehemoth, expectedRevision: 3,
      state: state({ inventory: [crossbow.item, bolt.item], tools: [crossbow.tool, bolt.tool] }), choice: 'face', ...titan
    });
    expect(face.value?.nextState.inventory.some(row => row.canonicalToolId === 'bolts')).toBe(false);
    expect(face.value?.nextState.inventory.some(row => row.canonicalReagentId === titan.reagentId)).toBe(true);
    expect(face.value?.directives).toEqual([]);
  });

  it('keeps p.173 reputation branches exclusive and provides a decline when Taxi cannot be paid', () => {
    const trustedTaxi = resolveFowlFare({ transactionId: 'fare:1', encounterId: 'foraging-meadow-8', expectedRevision: 3, state: state({ reputation: 35 }), choice: 'taxi' });
    expect(trustedTaxi).toMatchObject({ status: 'invalid', code: 'ineligible' });
    const decline = resolveFowlFare({ transactionId: 'fare:2', encounterId: 'foraging-meadow-8', expectedRevision: 3, state: state({ trinkets: 0 }), choice: 'decline' });
    expect(decline.status).toBe('resolved');
    expect(decline.value?.nextState.foragingPoints).toBe(2);
  });

  it('p.173 Going for Broke failure discards every Reagent unit and preserves non-Reagents', () => {
    const first = canonicalEncounterPartCandidates({ region: 'Meadow', maximumRarity: 12, types: ['PLANT', 'INSECT'] })[0];
    const existing = inventoryPart('stack', 'Beech', undefined, 4);
    const tool = canonicalTool('camp-kettle');
    const failed = resolveAntHeist({
      transactionId: 'ants:1', encounterId: FORAGING_ENCOUNTER_IDS.antHeist, expectedRevision: 3,
      state: state({ inventory: [existing, tool.item], tools: [tool.tool] }),
      firstCard: { value: 12, suit: '♥' }, firstPart: first, secondCard: { value: 4, suit: '♦' }
    });
    expect(failed.value?.nextState.inventory).toEqual([tool.item]);
    expect(failed.value?.nextState.tools).toHaveLength(1);
  });

  it('defers p.174 Reputation until the linked Guild Rumour reaches a Settlement exactly once', () => {
    const pickup = resolveProjectLaunch({
      transactionId: 'project:1', encounterId: FORAGING_ENCOUNTER_IDS.projectLaunch, expectedRevision: 3,
      state: state(), choice: 'watch'
    });
    const picked = pickup.value!.nextState;
    expect(picked.reputation).toBe(15);
    expect(picked.patient?.timers.map(row => row.current)).toEqual([4, 0]);
    expect(picked.inventory[0]).toMatchObject({ name: 'Guild Rumour', weight: 0 });

    const wrongPlace = deliverEncounterPayload({
      transactionId: 'project:city', encounterId: 'encounter-delivery', expectedRevision: picked.revision,
      state: picked, deliveryId: picked.deliveries[0].id, currentLocationId: 'odoak', currentLocationType: 'City'
    });
    expect(wrongPlace).toMatchObject({ status: 'invalid', code: 'ineligible' });

    const delivered = deliverEncounterPayload({
      transactionId: 'project:delivery', encounterId: 'encounter-delivery', expectedRevision: picked.revision,
      state: picked, deliveryId: picked.deliveries[0].id, currentLocationId: 'nearby-village', currentLocationType: 'Settlement'
    });
    expect(delivered.value?.nextState.reputation).toBe(17);
    expect(delivered.value?.nextState.inventory).toHaveLength(0);
    const replay = deliverEncounterPayload({
      transactionId: 'project:delivery-2', encounterId: 'encounter-delivery', expectedRevision: delivered.value!.nextState.revision,
      state: delivered.value!.nextState, deliveryId: picked.deliveries[0].id, currentLocationId: 'nearby-village', currentLocationType: 'Settlement'
    });
    expect(replay).toMatchObject({ status: 'invalid', code: 'invalid-selection' });
  });

  it('applies p.176 Calendar branches exclusively and gates Beseech at Upstanding', () => {
    const mushroom = canonicalEncounterPartCandidates({ mushroomsOnly: true })[0];
    const early = resolveMycophiliacs({
      transactionId: 'myco:1', encounterId: FORAGING_ENCOUNTER_IDS.mycophiliacs, expectedRevision: 3, state: state({ reputation: 25 }),
      locationId: 'meadow:1', calendarDaysTotal: 12, daysMarkedAtEncounterStart: 4, ...mushroom, beseech: true
    });
    expect(early.value?.nextState.inventory).toHaveLength(1);
    expect(early.value?.nextState.conditions).toContain('mycophiliacs:mushroom-barter-once:meadow:1');
    expect(early.value?.nextState.conditions.some(row => row.includes('rarity-10'))).toBe(false);

    const picked = resolveMycophiliacs({
      transactionId: 'myco:2', encounterId: FORAGING_ENCOUNTER_IDS.mycophiliacs, expectedRevision: 3, state: state(),
      locationId: 'meadow:1', calendarDaysTotal: 12, daysMarkedAtEncounterStart: 7
    });
    expect(picked.value?.nextState.conditions).toContain('mycophiliacs:mushroom-rarity-10:meadow:1');

    const tie = resolveMycophiliacs({
      transactionId: 'myco:3', encounterId: FORAGING_ENCOUNTER_IDS.mycophiliacs, expectedRevision: 3, state: state(),
      locationId: 'meadow:1', calendarDaysTotal: 12, daysMarkedAtEncounterStart: 6
    });
    expect(tie.value?.nextState.inventory).toEqual([]);
    expect(tie.value?.nextState.conditions).toEqual([]);

    const trustedBeseech = resolveMycophiliacs({
      transactionId: 'myco:4', encounterId: FORAGING_ENCOUNTER_IDS.mycophiliacs, expectedRevision: 3,
      state: state({ reputation: 35 }), locationId: 'meadow:1', calendarDaysTotal: 12,
      daysMarkedAtEncounterStart: 6, beseech: true
    });
    expect(trustedBeseech).toMatchObject({ status: 'invalid', code: 'ineligible' });
  });

  it('applies and consumes p.176 Location-scoped Mushroom effects without leaking to other Reagents or Locations', () => {
    const mushroom = canonicalEncounterPartCandidates({ mushroomsOnly: true })[0];
    const nonMushroom = canonicalEncounterPartCandidates({ mushroomsOnly: false }).find(candidate => {
      const reagent = REAGENT_BY_ID.get(candidate.reagentId);
      return reagent && !reagent.preparations.some(preparation => preparation.name === 'Mushroom')
        && !/mushroom|fungus|blewit|waxcap|deathcap|polypore/i.test(`${reagent.canonicalName} ${reagent.description}`);
    })!;
    const conditions = [
      'mycophiliacs:mushroom-rarity-10:meadow:1',
      'mycophiliacs:mushroom-barter-once:meadow:1',
      'unrelated-condition'
    ];

    expect(applyMycophiliacsMushroomRarity({
      conditions, currentLocationId: 'meadow:1', reagentId: mushroom.reagentId, baseRarity: 3
    })).toBe(10);
    expect(applyMycophiliacsMushroomRarity({
      conditions, currentLocationId: 'meadow:2', reagentId: mushroom.reagentId, baseRarity: 3
    })).toBe(3);
    expect(applyMycophiliacsMushroomRarity({
      conditions, currentLocationId: 'meadow:1', reagentId: nonMushroom.reagentId, baseRarity: 3
    })).toBe(3);

    const invalidBarter = consumeMycophiliacsMushroomBarter({
      conditions, currentLocationId: 'meadow:1', reagentId: nonMushroom.reagentId
    });
    expect(invalidBarter).toEqual({ consumed: false, conditions });

    const barter = consumeMycophiliacsMushroomBarter({
      conditions, currentLocationId: 'meadow:1', reagentId: mushroom.reagentId
    });
    expect(barter.consumed).toBe(true);
    expect(barter.conditions).toEqual([
      'mycophiliacs:mushroom-rarity-10:meadow:1',
      'unrelated-condition'
    ]);
    expect(consumeMycophiliacsMushroomBarter({
      conditions: barter.conditions, currentLocationId: 'meadow:1', reagentId: mushroom.reagentId
    }).consumed).toBe(false);

    expect(clearMycophiliacsLocationConditions(conditions, 'meadow:1')).toEqual(['unrelated-condition']);
  });

  it('p.177 Take gains exactly Charcoal and Hair/Fur once', () => {
    const charcoal = part('Doused Bonfires', 'Charcoal');
    const sheddings = part('Animal Sheddings', 'Hair');
    const result = resolveLifeSavingTransplant({
      transactionId: 'transplant:1', encounterId: FORAGING_ENCOUNTER_IDS.lifeSavingTransplant, expectedRevision: 3, state: state(),
      charcoalPreparationId: charcoal.preparationId, sheddingsPreparationId: sheddings.preparationId
    });
    expect(result.value?.nextState.inventory).toHaveLength(2);
    expect(result.value?.nextState.inventory.map(row => row.preparationId)).toEqual([charcoal.preparationId, sheddings.preparationId]);
    expect(result.value?.nextState.reputation).toBe(15);
  });

  it('persists p.177 target cards, prevents duplicate matches, and gives one Tool for all three returns', () => {
    const started = startSainDeClawsQuest({
      transactionId: 'sain:1', encounterId: 'foraging-meadow-9-winter', expectedRevision: 3, state: state(), locationId: 'meadow:1',
      targetCards: [{ value: 2, suit: '♥' }, { value: 5, suit: '♦' }, { value: 9, suit: '♣' }]
    });
    let current = started.value!.nextState;
    const questId = current.sainDeClawsQuests[0].id;
    for (let index = 0; index < 3; index += 1) {
      const match = recordSainDeClawsMatch({
        transactionId: `sain:match:${index}`, encounterId: 'sain-de-claws-match', expectedRevision: current.revision, state: current,
        questId, forageTransactionId: `forage:${index}`, locationId: 'meadow:1', forageCard: { value: [2, 5, 9][index], suit: '♠' }, targetIndex: index
      });
      current = match.value!.nextState;
    }
    const reusedForageCard = recordSainDeClawsMatch({
      transactionId: 'sain:match:forged-second-present', encounterId: 'sain-de-claws-match', expectedRevision: current.revision, state: current,
      questId, forageTransactionId: 'forage:0', locationId: 'meadow:1', forageCard: { value: 5, suit: '♥' }, targetIndex: 1
    });
    expect(reusedForageCard).toMatchObject({ status: 'invalid', code: 'already-applied' });
    const returned = returnSainDeClawsPresents({
      transactionId: 'sain:return', encounterId: 'sain-de-claws-return', expectedRevision: current.revision, state: current,
      questId, locationId: 'meadow:1', targetIndexes: [0, 1, 2]
    });
    current = returned.value!.nextState;
    const reward = settleSainDeClawsAtSeasonEnd({
      transactionId: 'sain:reward', encounterId: 'sain-de-claws-season-end', expectedRevision: current.revision, state: current,
      questId, atSeasonEnd: true, toolId: 'canvas-tent'
    });
    expect(reward.value?.nextState.inventory).toHaveLength(1);
    expect(reward.value?.nextState.inventory[0].canonicalToolId).toBe('canvas-tent');
    expect(reward.value?.nextState.trinkets).toBe(4);

    const bodyPartIsNotAReward = settleSainDeClawsAtSeasonEnd({
      transactionId: 'sain:invalid-reward', encounterId: 'sain-de-claws-season-end',
      expectedRevision: current.revision, state: current, questId, atSeasonEnd: true, toolId: 'paws'
    });
    expect(bodyPartIsNotAReward).toMatchObject({ status: 'invalid', code: 'invalid-selection' });
  });

  it('p.179 loss clears every Bag unit, Tool state, and Trinket; win grants the restricted Weapon', () => {
    const tool = canonicalTool('canvas-tent');
    const bag = [tool.item, inventoryPart('part:1', 'Beech', undefined, 3), { id: 'item:1', name: 'Food', type: 'item', weight: 1 } satisfies EngineInventoryItem];
    const safe = resolveStickEmUp({
      transactionId: 'stick:safe', encounterId: FORAGING_ENCOUNTER_IDS.stickEmUp, expectedRevision: 3,
      state: state({ inventory: bag, tools: [tool.tool], trinkets: 7 }), choice: 'play-safe'
    });
    expect(safe.value?.nextState).toMatchObject({ inventory: [], tools: [], trinkets: 0 });

    const win = resolveStickEmUp({
      transactionId: 'stick:win', encounterId: FORAGING_ENCOUNTER_IDS.stickEmUp, expectedRevision: 3,
      state: state(), choice: 'scrap', playerCards: [{ value: 12, suit: '♥' }],
      robberCards: [{ value: 4, suit: '♣' }, { value: 8, suit: '♠' }], usedCrossbowExtraDraw: false
    });
    expect(win.value?.nextState.inventory[0]).toMatchObject({ weight: 1, encounterMetadata: { kind: 'weapon', worksAgainst: ['Beast'] } });
  });

  it('p.185 resolves an unsafe chamber entry as flight with no reward and grants exactly one canonical reward on entry', () => {
    const unsafe = resolveFinalRestingPlace({
      transactionId: 'rest:1', encounterId: FORAGING_ENCOUNTER_IDS.finalRestingPlace, expectedRevision: 3, state: state(),
      card: { value: 5, suit: '♠' }, companionCapacity: 1
    });
    expect(unsafe).toMatchObject({ status: 'resolved' });
    expect(unsafe.value?.nextState).toMatchObject({ companions: [], inventory: [] });

    const forgedReward = resolveFinalRestingPlace({
      transactionId: 'rest:forged', encounterId: FORAGING_ENCOUNTER_IDS.finalRestingPlace, expectedRevision: 3, state: state(),
      card: { value: 5, suit: '♠' }, reward: { kind: 'companion' }, companionCapacity: 1
    });
    expect(forgedReward).toMatchObject({ status: 'invalid', code: 'ineligible' });

    const thing = canonicalTool('titan-thingamabob');
    const success = resolveFinalRestingPlace({
      transactionId: 'rest:2', encounterId: FORAGING_ENCOUNTER_IDS.finalRestingPlace, expectedRevision: 3,
      state: state({ inventory: [thing.item], tools: [thing.tool] }), card: { value: 5, suit: '♣' }, reward: { kind: 'companion' }, companionCapacity: 1
    });
    expect(success.value?.nextState.companions.map(row => row.companionId)).toEqual(['cranky-contraption']);
    expect(success.value?.nextState.inventory.some(row => row.canonicalToolId === 'titan-thingamabob')).toBe(true);
  });

  it('p.186 grants no immediate Reputation and later awards +4/+6 only with the exact borrowed Tool', () => {
    const found = resolveWhatRemains({
      transactionId: 'remains:1', encounterId: FORAGING_ENCOUNTER_IDS.whatRemains, expectedRevision: 3, state: state(),
      card: { value: 7, suit: '♥' }, homeLocationId: 'summit', borrowedToolId: 'copper-frying-pan'
    });
    let current = found.value!.nextState;
    expect(current.reputation).toBe(15);
    const delivery = current.deliveries[0];
    const wrongPlace = deliverEncounterPayload({
      transactionId: 'remains:wrong', encounterId: 'encounter-delivery', expectedRevision: current.revision, state: current,
      deliveryId: delivery.id, currentLocationId: 'odoak', currentLocationType: 'City', returnBorrowedTool: true
    });
    expect(wrongPlace).toMatchObject({ status: 'invalid', code: 'ineligible' });
    const delivered = deliverEncounterPayload({
      transactionId: 'remains:deliver', encounterId: 'encounter-delivery', expectedRevision: current.revision, state: current,
      deliveryId: delivery.id, currentLocationId: 'summit', currentLocationType: 'City', returnBorrowedTool: true
    });
    expect(delivered.value?.nextState.reputation).toBe(25);
    expect(delivered.value?.nextState.inventory).toHaveLength(0);
    expect(delivered.value?.nextState.tools).toHaveLength(0);
  });

  it('p.186 Lock and Key validates but does not consume the Thingamabob', () => {
    const thing = canonicalTool('titan-thingamabob');
    const result = resolveLockAndKey({
      transactionId: 'lock:1', encounterId: 'foraging-titan-6', expectedRevision: 3,
      state: state({ inventory: [thing.item], tools: [thing.tool] }), choice: 'light', locationId: 'titan:1'
    });
    expect(result.value?.nextState.conditions).toContain('manual:foraging-titan-6:lock-and-key:encounter-foraging-points-until-move:titan:1');
    expect(result.value?.nextState.inventory).toHaveLength(1);
  });

  it('p.187 decreases the selected Timer on every rescue attempt and gates Bakar by exact ruin', () => {
    const failed = resolveTrapped({
      transactionId: 'trapped:1', encounterId: TRAPPED_ENCOUNTER_IDS[0], expectedRevision: 3, state: state(),
      choice: 'rescue', card: { value: 4, suit: '♠' }, timerId: 'timer-2'
    });
    expect(failed.value?.nextState.patient?.timers.map(row => row.current)).toEqual([6, 1]);
    expect(failed.value?.nextState.reputation).toBe(15);
    expect(failed.value?.directives).toContainEqual({ kind: 'may-retry-trapped-rescue', sourcePage: 187 });

    const wrongRuin = resolveTrapped({
      transactionId: 'trapped:2', encounterId: TRAPPED_ENCOUNTER_IDS[0], expectedRevision: 3,
      state: state({ conditions: ['bakar:met-in-ruin:titan:1'] }), choice: 'helping-hand', locationId: 'titan:2'
    });
    expect(wrongRuin).toMatchObject({ status: 'invalid', code: 'ineligible' });
  });

  it('p.187 Meek Shall Inherit cannot forge a Reagent outside its chosen list', () => {
    const beetle = part('Beetles');
    const valid = resolveMeekShallInherit({
      transactionId: 'meek:1', encounterId: MEEK_ENCOUNTER_IDS[0], expectedRevision: 3, state: state(), search: 'stunned', ...beetle
    });
    expect(valid.value?.nextState.inventory).toHaveLength(1);
    const slug = part('Slugs');
    const forged = resolveMeekShallInherit({
      transactionId: 'meek:2', encounterId: MEEK_ENCOUNTER_IDS[0], expectedRevision: 3, state: state(), search: 'stunned', ...slug
    });
    expect(forged).toMatchObject({ status: 'invalid', code: 'invalid-selection' });
  });

  it('p.195 swaps one carried non-basic Tool atomically and rejects forged source IDs', () => {
    const source = canonicalTool('canvas-tent');
    const swap = resolveOdoakMarket({
      transactionId: 'market:1', encounterId: FORAGING_ENCOUNTER_IDS.odoakMarket, expectedRevision: 3,
      state: state({ inventory: [source.item], tools: [source.tool] }), choice: 'irresistible-bargain',
      sourceToolItemId: source.item.id, targetToolId: 'copper-frying-pan'
    });
    expect(swap.value?.nextState.inventory.map(row => row.canonicalToolId)).toEqual(['copper-frying-pan']);
    expect(swap.value?.nextState.tools.map(row => row.toolId)).toEqual(['copper-frying-pan']);

    const forged = resolveOdoakMarket({
      transactionId: 'market:2', encounterId: FORAGING_ENCOUNTER_IDS.odoakMarket, expectedRevision: 3,
      state: state({ inventory: [source.item], tools: [source.tool] }), choice: 'irresistible-bargain',
      sourceToolItemId: 'missing', targetToolId: 'copper-frying-pan'
    });
    expect(forged).toMatchObject({ status: 'invalid', code: 'invalid-selection' });
  });

  it('p.195 charges exactly two Trinkets and persists the chosen Foreign Reagent fields', () => {
    const multipleMethods = resolveOdoakMarket({
      transactionId: 'market:foreign', encounterId: FORAGING_ENCOUNTER_IDS.odoakMarket, expectedRevision: 3,
      state: state(), choice: 'impulse-purchase', reagentName: 'Moon Pepper', reagentType: 'PLANT', tag: 'BURN',
      preparationMethods: ['BREWED', 'BREWED', 'CRUSHED']
    });
    expect(multipleMethods).toMatchObject({ status: 'invalid', code: 'invalid-selection' });

    const bought = resolveOdoakMarket({
      transactionId: 'market:foreign:valid', encounterId: FORAGING_ENCOUNTER_IDS.odoakMarket, expectedRevision: 3,
      state: state(), choice: 'impulse-purchase', reagentName: 'Moon Pepper', reagentType: 'PLANT', tag: 'BURN',
      preparationMethods: ['BREWED']
    });
    expect(bought.value?.nextState.trinkets).toBe(2);
    expect(bought.value?.nextState.inventory[0]).toMatchObject({
      weight: 2 / 3,
      customReagent: { targetTag: 'BURN', preparation: 'BREWED' },
      encounterMetadata: {
        kind: 'foreign-reagent', reagentType: 'PLANT', tagPotency: 2,
        preparationMethods: ['BREWED']
      }
    });
  });
});
