// Encounter names are compact display labels, not rules text. Keeping them in a
// dedicated table prevents the rulebook's decorative English headings and OCR
// line breaks from leaking into Korean play dialogs.
export const ENCOUNTER_TITLE_KO: Record<string, string> = {
  Wisps: '도깨비불',
  'From Rot Comes Art': '썩은 것에서 피어난 예술',
  'Branch-Beaten': '나뭇가지에 두들겨 맞다',
  'Climate Change': '날씨의 변덕',
  'Friend In The Mists': '안개 속의 친구',
  'That Sucks': '흡혈객',
  'Pumped Up Cafe': '활기찬 카페',
  'Blood On The Ice': '얼음 위의 피',
  'Pottering About': '도자기 빚기',
  Mudlarking: '진흙 속 보물찾기',
  'Chilled To The Core': '뼛속까지 얼어붙다',
  'Fungi Founder': '새 버섯의 발견자',
  Hardpacked: '단단히 얼어붙은 길',
  'Busy Work': '바쁜 일손',
  'On The Path': '길 위에서',
  'In Bloom': '꽃이 한창',
  'Rest Stop': '길가의 쉼터',
  'Hot Tea': '따뜻한 차',
  'From Up On High': '높은 곳에서',
  Memories: '추억',
  'Typical Summer': '흔한 여름날',
  Wayfriend: '길 위의 친구',
  Fairwinders: '순풍을 타는 이들',
  'Freshly Grilled': '갓 구운 요리',
  'Danger Ahead': '앞길의 위험',
  'Turning Fortune': '뒤바뀐 운수',
  Piledriver: '거대한 발자국',
  Parade: '축제 행렬',
  'Go Ape': '나무 위 모험',
  'Lost-And-Found': '분실물 보관소',
  'Hunger Pains': '굶주림의 고통',
  Undercurrent: '거센 물밑 흐름',
  'Muddy Waters': '흐린 물속',
  'Carpe Carp-ey': '잉어를 잡아라',
  'Push and Pull': '밀고 당기는 물살',
  'Less Than Titanic': '가라앉는 표류물',
  'Log Floats': '통나무 뗏목',
  'Snarling Threats': '으르렁대는 위협',
  'Figure Skating': '얼음 위의 곡예',
  'Need For Speed': '속도 승부',
  'Pi-rats!': '해적 쥐떼!',
  'Winged Menace': '날개 달린 위협',
  Frostbitten: '동상',
  Cruise: '아름다운 유람선',
  'Vicious Murk': '위험한 녹조',
  'Hospitality, Eh?': '따뜻한 환대',
  'Two-Faced': '엇갈린 증언',
  Obstruction: '가로막힌 길',
  Roadtreat: '길 위의 간식',
  'Brick By Brick': '벽돌 한 장씩',
  "Sorry, We've Misplaced Your Order": '죄송합니다, 배달물이 바뀌었어요',
  'Highway Robbery': '꼬마 산적의 통행세',
  'Rooting Around': '들판을 헤집는 멧돼지',
  Deluge: '폭우',
  'Alls Fair In Snow And War': '눈싸움에는 반칙이 없다',
  'Returning Songbirds': '돌아온 철새들',
  'Animal Crossing': '야수들의 행렬',
  'Ghost Tales': '유령 이야기',
  'Snow Clan': '눈으로 만든 야수',
  'Hired Paws': '일손을 빌려드립니다',
  Cowtown: '움직이는 소 마을',
  'All Paws Appreciated': '모든 일손을 환영합니다',
  Solitude: '고요한 설원',
  'What Goes Up': '올라간 것은 내려온다',
  "Magpie's Mark": '까치의 표식',
  'Break With A View': '전망 좋은 휴식',
  'Pretty Prickles': '아름다운 가시덤불',
  'Yodelling Gorillas': '요들 부르는 고릴라들',
  'Dastards Ahead': '악당들의 모의',
  'Knights Of The Round Table': '원탁의 기사들',
  'Parched!': '목이 말라!',
  Tobogganing: '썰매 타기',
  'Red Sky At Night': '저녁놀',
  'Springmel t': '봄눈 녹은 물',
  'Springmelt': '봄눈 녹은 물',
  'Squeaky Wheels': '삐걱대는 바퀴',
  'Treacherous Footing': '위태로운 발밑',
  'Do You Nose Your Herbs?': '약초 향을 아시나요?',
  Gale: '돌풍',
  'Swift Journey': '순풍의 여정',
  Unbuckled: '풀린 버클',
  'Less Than Majestic': '볼품없는 비행',
  Talons: '날카로운 발톱',
  'Silent Observer': '말없는 관찰자',
  'The Water Cycle': '물의 순환',
  'Glimpses Of Elsewhere': '먼 세계의 풍경',
  'High Above It All': '모든 것보다 높이',
  Windwall: '바람의 벽',
  Hailstorm: '우박 폭풍',
  Jitterbug: '덜컹거리는 괴물',
  'Base Camp': '탐사대 야영지',
  'Can It': '통조림 통',
  'Grim Opening': '불길한 입구',
  'Fabled Place': '전설 속 장소',
  Siren: '사이렌',
  'Electrician, or Electrocuted?': '전기 기술자, 아니면 감전 사고?',
  'Mind Yerself!': '발밑 조심!',
  'Ancient Salvage': '고대의 인양물',
  'Bridge Across The Water': '물 위의 다리',
  "The Rattlin' Bog": '달그락거리는 습지',
  Repellent: '퇴치제',
  'Even The Mighty Fall': '강한 자도 쓰러진다',
  'Squelch!': '철퍽!',
  'Right Place, Wrong Time': '잘못 찾아온 순간',
  'Guild of One': '혼자뿐인 길드',
  'A Thousand Thousand Biters': '수없이 많은 흡혈충',
  'Rusty Pick': '녹슨 곡괭이',
  'Chestnuts On An Open Fire': '모닥불에 구운 밤',
  Weaver: '거미줄 직조가',
  'Midges!': '각다귀 떼!',
  'Heat Sink': '얼음물 속으로',
  'Fluttering Fancy': '나풀대는 환상',
  'Aerial Support': '하늘의 지원대',
  'Storm Front': '폭풍 전선',
  'The Right Thing': '옳은 일',
  'Legacy In Mud': '진흙 속 유산',
  'Fangs With Wings': '날개 달린 송곳니',
  'Duchy of Deer': '사슴 공작령',
  'New Route': '새로운 길',
  'Fowl Language': '버릇없는 새',
  'The Collector': '수집가',
  'Mushroom Pickers': '버섯 채집꾼들',
  'Dam Lotta Trouble': '댐 때문에 골치 아파',
  'Log Knocking': '썩은 통나무 뒤집기',
  'Petty Squabbles': '사소한 다툼',
  'Friend In Need': '도움이 필요한 동료',
  'The Branded': '낙인찍힌 야수',
  'A Convenient Deal': '마침 좋은 거래',
  'If You Go Down To The Woods Today': '오늘 숲에 들어간다면',
  'Blades of the Boreal Dancer': '북풍 무희의 칼날',
  'Alluring Odours': '매혹적인 향기',
  Siesta: '낮잠',
  'An Unlikely Friend': '뜻밖의 친구',
  'White Out': '백색 시야',
  'Not Forgotten': '잊히지 않은 이',
  'Thief!': '도둑이야!',
  'Competitive Spirit': '경쟁심',
  'Winter Feast': '겨울 잔치',
  "Bear's Necessities": '곰에게 꼭 필요한 것',
  'Stung On All Sides': '사방이 따끔따끔',
  'Musty!': '퀴퀴한 향!',
  "Fangs a'Hungering": '굶주린 송곳니',
  'Horrors From The Deep': '깊은 곳에서 온 공포',
  "Bonepickin'": '생선 뼈 고르기',
  'Lost and Found': '잃어버린 물건',
  'Stretch And Release': '몸을 풀고 놓아주기',
  Serenity: '고요',
  Fogbank: '짙은 안개',
  'Fish Slap': '연어의 일격',
  'Voyage To The Blackwater': '검은 물로 떠나는 장례',
  'Froglets!': '아기 개구리들!',
  'A Small Ailment': '작은 환자',
  'The Great Silence': '거대한 정적',
  'Thin Ice': '얇은 얼음',
  'River Snatchers': '강물의 도둑들',
  'Summertime Swim': '여름날의 물놀이',
  'The Boat That Rocks': '흔들리는 파티 배',
  Showboat: '화려한 배',
  Flood: '범람',
  'Brisk Beach Party': '쌀쌀한 물가 파티',
  'A Gentle Moment': '평온한 한때',
  'Up To Something': '수상한 꿍꿍이',
  'Fabled Behemoth': '전설의 거수',
  'Lodge of Wonders': '경이로운 비버집',
  'Soft Song': '부드러운 노래',
  'Cow Tools?': '소의 농기구?',
  'Little Biters': '작은 흡혈충',
  'The Winged Hunter': '날개 달린 사냥꾼',
  'Pest Control': '해충 방지',
  'Ant Heist!': '개미들의 대도둑질!',
  'Wild Chef': '야생의 요리사',
  'Fowl Fare': '새가 건넨 먹거리',
  'Project Launch': '신작 공개',
  'Misbehooving Behemoths': '말썽꾸러기 거수들',
  'Sloppy Steps': '질척이는 길',
  'Sain De Claws': '초록 모자의 선물꾼',
  "One Beast's Rubbish": '어떤 야수의 쓰레기',
  'Unyielding Heat': '가시지 않는 열기',
  'Heavy Fog': '짙은 안개',
  'A Worrying Ache': '걱정스러운 통증',
  'Grind Mentality': '쉬지 않는 일손',
  'Bee Kind To Yourself': '자신에게도 다정하게',
  'Trembling Titan Technology': '진동하는 타이탄 기술',
  'Social Occasion': '작은 사교 모임',
  Sowing: '씨 뿌리기',
  'Fire and Iron': '불꽃과 강철',
  Mycophiliacs: '버섯 애호가들',
  'Life Saving Transplant': '목숨을 살리는 이식',
  'A Sign To Nowhere': '아무 데도 향하지 않는 표지판',
  'A Pleasant Surprise': '기분 좋은 뜻밖의 발견',
  "Konami's Path": '코나미의 길',
  'When You Look Up, You Will Find Me': '고개를 들면 나를 찾으리',
  'The Height Of Wit': '높은 곳의 재치',
  'Flock Full Of Trouble': '말썽 가득한 새 떼',
  "Stick 'Em Up!": '꼼짝 마!',
  'Coursing River': '내달리는 강물',
  'Arena of the Mind': '마음속 경기장',
  'Softened Sensations': '무뎌진 감각',
  'Mountain Rescue': '산악 구조',
  'Special Technique': '특별한 기술',
  'Refreshing Drink': '상쾌한 한 모금',
  Howl: '멀리서 들리는 울음',
  'Chilled To The Bone': '뼛속까지 시리다',
  'Protective Parents': '과보호 부모들',
  'Moment of Clarity': '또렷해지는 순간',
  'Gather At The Tree': '나무 아래 모이다',
  'Speed of Sound': '소리의 속도',
  'Ray Tracing': '한 줄기 빛',
  'Blazing Sun': '타오르는 햇빛',
  Dreich: '음산한 날씨',
  'Mercy For The Mighty': '강대한 이에게 자비를',
  'A Message': '전언',
  Password: '암호',
  'Gas Leak': '가스 누출',
  'Final Resting Place': '마지막 안식처',
  'Malevolence Grafted To Metal': '금속에 접붙인 악의',
  'Lock And Key': '자물쇠와 열쇠',
  'What Remains': '남겨진 것',
  'Snap, Crackle, Pop!': '딱, 따닥, 펑!',
  'False Idols': '거짓 우상',
  'The Meek Shall Inherit': '온순한 이들의 유산',
  Trapped: '갇힘',
  'The Researcher': '연구자',
  'Reed Harvesting': '갈대 수확',
  Preserved: '보존 식품',
  Airborne: '하늘길',
  Florist: '꽃장수',
  'Diving Birds': '잠수하는 새들',
  Training: '훈련',
  'Essence, in Oil': '기름에 담긴 정수',
  Insulation: '단열',
  'Hot Pocket': '따뜻한 주머니',
  'The Bog Gives': '습지가 내어주는 것',
  Stagnant: '고인 물',
  'Marsh Wader': '습지를 걷는 새',
  'Tree Lift': '나무 승강기',
  Bridges: '다리들',
  Market: '시장',
  'Orebeater Forges': '광석장이의 대장간',
  'Cul tivation': '가지 가꾸기',
  Cultivation: '가지 가꾸기',
  'To Glide, or not to Glide': '활공할까, 말까',
  'Betting Match': '내기 경기',
  'Deep Fried Delicacy': '바삭하게 튀긴 별미',
  Duty: '의무',
  Sauna: '한증욕',
  'Tall Tales': '허풍 이야기',
  'Spike Defence': '가시 방어선',
  'Woven Strands': '촘촘히 엮은 실',
  'Fresh Catch': '갓 잡은 먹거리',
  Boatmakers: '배 만드는 이들',
  Nursery: '보육소',
  Interior: '선박 내부',
  Exterior: '선박 외부',
  'Luminescent Orb': '빛나는 구슬',
  'Carved in Bone': '뼈에 새긴 조각',
  Maintenance: '정비 작업',
  Waterdancers: '물 위의 무희들',
  'Clammed Up': '조개를 깨다',
  'Oak Smoker': '참나무 훈연',
  Shanty: '뱃노래',
  Cranky: '심술궂은 손님',
  Inspection: '가방 검역',
  Monuments: '기념물',
  Navigation: '길 찾기',
  Junction: '갈림길',
  'Emerging Bud': '피어나는 새싹',
  'Bees!': '벌 떼!',
  'Emergency Care': '응급 처치',
  'A Web For Charlotte': '샬럿을 위한 거미줄',
  Calvinball: '캘빈볼',
  BRB: '잠시 후에',
  'Keen Reading': '예리한 독서',
  Pawprint: '발자국',
  'Shift Change': '교대 시간',
  'Getting Around': '도시를 오가는 법',
  Linen: '리넨 직물',
  Thinkers: '사색가들',
  Refresh: '재충전',
  'Grinding Ore': '광석 빻기',
  Echo: '메아리',
  'Cliff Dancing': '절벽 춤',
  'Carved in Stone': '돌에 새기다',
  Panning: '사금 채취',
  'Hot Toddy': '따뜻한 토디차',
  'Warm Embrace': '따뜻한 포옹',
  'Domestic Salmon': '양식 연어',
  'Done-deal': '거래 성사',
  Glassblowers: '유리 공예가들',
  'Wandering The City': '도시 산책'
};
