// Reading-layer translations. Canonical IDs, numbers and engine definitions remain unchanged.
export const CATALOGUE_READING_KO: Readonly<Record<string, { title: string; summary: string; unlock?: string }>> = {
  'service:send-package': { title: '소포 보내기', summary: '무게 합계 5 이하의 물품을 다른 플레이어에게 보냅니다. 수신자가 다음 정착지나 도시에 들어갈 때 받습니다.' },
  'service:rug-of-wonders': { title: '놀라운 양탄자', summary: '여정당 한 번, 기본 희귀도 9 이하인 영약재에서 부위 하나를 얻습니다. 티탄 영약재도 해당합니다.' },
  'service:news-from-the-trail': { title: '길 위의 소식', summary: '여정 목적지에 도착하기 전 이동 조우를 한 번 다시 뽑고, 두 카드 중 하나를 고릅니다.' },
  'service:smithing': { title: '철공 개조', summary: '보유한 기본 도구 하나를 호환되는 개조품으로 바꿉니다. 산악 정착지뿐 아니라 어느 도시에서든 이용합니다.' },
  'service:forecast': { title: '날씨 예보', summary: '다음 세 번의 이동 동안 날씨 태그 채집 조우의 부정적인 효과를 무시합니다.' },
  'service:catch-of-the-day': { title: '오늘의 물고기', summary: '장신구 1개로 작은 물고기 부위 하나, 또는 장신구 2개로 큰 물고기 부위 하나를 얻습니다.' },
  'service:shortcut': { title: '숨은 지름길', summary: '연결된 경로가 없어도 가까운 위치 하나로 즉시 이동합니다.' },
  'service:hitch-a-ride': { title: '농부 마차 얻어타기', summary: '다음 이동은 최대 5경로이며 초원에서 끝나야 합니다. 이동 조우 대신 함께 탄 농부 이야기를 일지에 남깁니다.' },
  'service:survey-paths': { title: '경로 측량', summary: '가까운 두 위치 사이에 경로를 추가하거나, 한 위치를 기존 경로에 연결합니다.' },
  'service:build-a-bridge': { title: '다리 건설', summary: '호수 위치 하나를 거쳐 서로 다른 두 육지를 잇는 수로 두 개를 일반 경로로 바꿉니다.' },
  'service:floodplain': { title: '범람지 만들기', summary: '야생 위치 하나를 호수로 바꿉니다. 다음 봄에 원래 지역으로 돌아갑니다.' },
  'service:taxi-service': { title: '독수리 택시', summary: '다음 이동을 비행으로 수행하며 그 비행 조우의 부정적인 결과를 피합니다.' },
  'service:take-clippings': { title: '온실 꺾꽂이', summary: '원하는 식물 영약재에서 부위 하나를 얻습니다.' },
  'service:pick-of-the-deep': { title: '깊은 곳의 수확', summary: '카드를 뽑고 그 값 이하의 기본 희귀도를 가진 티탄 영약재에서 부위 하나를 얻습니다. M은 12입니다. 해당 영약재가 없으면 쓸 만한 수확은 없지만 비용은 지불합니다.' },
  'service:retrieval': { title: '회수 의뢰', summary: '티탄 이외의 영약재 또는 잃어버린 물건을 의뢰합니다. 적어도 5경로 떨어진 정착지에 맡겨 두면 도착해서 받습니다.' },
  'service:send-a-missive': { title: '전령 보내기', summary: '정착지를 최대 세 곳 지정합니다. 그곳에서 다음으로 접수할 질환을 직접 고를 수 있습니다.' },
  'service:scare-tactics': { title: '위협 제거', summary: '지도에 남은 거수 관련 효과나 고분 하나를 제거합니다.' },
  'clinic:pantry': { title: '식품 저장고', summary: '약제소에서 겨울잠을 잘 수 있습니다. 명예가 15 미만이면 동면하는 동물 한 명마다 장신구 15개를 냅니다.', unlock: '길드 명예 15 이상' },
  'clinic:library': { title: '도서실', summary: '질환을 알아볼 때 카드를 두 번 뽑고 하나를 고릅니다.', unlock: 'Summit 방문 및 휴식기 활동 ‘길드 동료들과 재회’ 완료' },
  'clinic:hive-boxes': { title: '벌집 상자', summary: '함께 여행하지 않는 동료를 맡기고, 어느 약제소에서든 교대할 수 있습니다.', unlock: 'Spoolkeep 방문' },
  'clinic:gardens': { title: '약초 정원', summary: '약제소마다 식물 하나를 기릅니다. 봄·여름·가을에 질환당 한 번 채집합니다.', unlock: 'Noonhill 방문' },
  'clinic:greenhouses': { title: '온실', summary: '약초 정원을 겨울에도 이용할 수 있습니다.', unlock: '약초 정원 보유 및 Glasswall 방문' },
  'clinic:sodden-logs': { title: '젖은 통나무', summary: '곤충 하나를 정합니다. 겨울을 제외하고 질환당 한 번 채집하며 모든 타이머를 1 줄입니다.', unlock: 'Odoak 방문' },
  'clinic:taproom': { title: '주점', summary: '계절이 끝날 때 약제소마다 장신구 1개를 얻습니다.', unlock: 'Vessel 방문' },
  'clinic:hostel': { title: '숙소', summary: '주점 수입을 약제소마다 장신구 2개로 바꿉니다. 기존 1개에 추가하는 것이 아닙니다.', unlock: '주점 보유' },
  'clinic:mailbox': { title: '우편함', summary: '길드 우편함을 통해 도움을 요청하는 편지를 받습니다.', unlock: '추가 조건 없음' },
  'clinic:goodwill-stand': { title: '나눔 가판대', summary: '물품을 기부합니다. 계절이 끝날 때 기부한 무게 1마다 길드 명예 1을 얻습니다.', unlock: '추가 조건 없음' },
  'wagon:base-unit': { title: '기본 마차', summary: '소지 한도 +4, 속도 +1. 가격은 원문 p.68의 15와 p.43의 20이 다릅니다. 앱의 휴식기 위탁은 p.43에 따라 20을 사용합니다.' },
  'wagon:side-brackets': { title: '측면 짐받이', summary: '마차의 소지 한도 보너스를 +4에서 +6으로 바꿉니다. 두 보너스를 합산하지 않습니다.' },
  'wagon:axel-springs': { title: '차축 스프링', summary: '마차의 속도 보너스를 +1에서 +2로 바꿉니다.' },
  'wagon:hive-brackets': { title: '벌집 짐받이', summary: '여행 동료를 최대 두 마리 데려갑니다.' },
  'wagon:sealed-carriage': { title: '밀폐식 마차와 돛', summary: '영약재를 잃지 않고 보통 속도로 수로를 건너며 호수에 멈출 수 있습니다. 나무껍질 배를 재활용하면 설치비가 10에서 5로 줄어듭니다.' },
  'wagon:pedal-motor': { title: '페달 모터', summary: '서로 이어진 수로 두 개를 수로 하나로 계산합니다.' },
  'wagon:experimental-contraption': { title: '실험용 비행 장치', summary: '마차로 비행할 수 있습니다. 비행 이동마다 1일 대신 3일을 기록합니다.' },
  'wagon:passenger-booth': { title: '승객 좌석', summary: '치료제를 거래한 뒤 승객 한 명을 태울 수 있습니다. 내려 주는 곳에 따라 장신구 1·2·4개 중 해당하는 가장 높은 요금 한 번을 받습니다.' },
  'wagon:clay-pots': { title: '진흙 화분', summary: '제철 식물 하나를 기릅니다. 첫 수확 후에는 두 번 이동해야 다시 채집할 수 있습니다.' },
  'wagon:shadow-canvas': { title: '그늘 천막', summary: '정착지에 도착할 때 길드 명예 1을 얻습니다.' },
  'companion:beetle': { title: '딱정벌레', summary: '여정당 한 번, 공격적인 동물이 등장하는 조우를 무시합니다.' },
  'companion:butterfly': { title: '나비', summary: '봄과 여름에 식물 영약재의 희귀도를 1 낮춥니다.' },
  'companion:caterpillar': { title: '애벌레', summary: '가벼운 질환과 보통 질환의 시작 타이머에 1을 더합니다. 한 계절 뒤 나비가 됩니다.' },
  'companion:cranky-contraption': { title: '삐걱대는 장치', summary: '장치를 희생하여 거수 조우에서 벗어나고 부정적 결과를 피합니다. 사용한 동료는 사라집니다.' },
  'companion:cricket': { title: '귀뚜라미', summary: '악기가 있으면 추가 악기 하나와 그것을 연주할 발 한 쌍으로 셉니다.' },
  'companion:honeybee': { title: '꿀벌', summary: '10경로를 이동하면 벌집의 꿀 부위 하나를 얻습니다.' },
  'companion:pond-skimmer': { title: '소금쟁이', summary: '여정당 한 번 호수 이동 조우를 다시 뽑습니다.' },
  'companion:spider': { title: '거미', summary: '채집할 때 곤충 영약재의 희귀도를 1 낮춥니다.' },
  'companion:wasp': { title: '말벌', summary: '10경로를 이동하면 곤충 부위를 채집하는 것처럼 카드 한 장을 뽑습니다.' },
  'tool:steel-lined-mortar': { title: '강철 안감 절구와 공이', summary: '현지 환자를 돕는 동안 첫 GRIND·CRUSH 부위를 모으면 모든 활성 타이머가 1 늘어납니다.' },
  'tool:granite-mortar': { title: '화강암 절구와 공이', summary: '식물의 BREW 부위를 무게 없는 가루·차로 빻습니다. 소지 한도 수치만큼 보관합니다.' },
  'tool:pairing-knife': { title: '작은 손질칼', summary: '무게를 차지하지 않으면서 기본 칼처럼 채집 포인트를 얻을 수 있습니다.' },
  'tool:silver-sickle': { title: '은 낫', summary: '채집 포인트를 얻을 때마다 1점을 추가로 얻습니다.' },
  'tool:steel-axe': { title: '강철 도끼', summary: '질환이 시작될 때 채집 포인트 3점을 얻습니다.' },
  'tool:efficient-copper-kettle': { title: '고효율 구리 주전자', summary: 'BOIL·BREW 부위를 모을 때 타이머 하나에 1을 더합니다.' },
  'tool:double-boiler': { title: '이중 냄비', summary: '치료제에 BOIL·BREW 부위가 하나뿐이면 그 부위의 약효를 1 높입니다.' },
  'barrow:uneasy-sleep': { title: '불안한 잠', summary: '수면 향 만들기: 타이머 4 안에 SLEEP 합계 6을 준비합니다. 이 고분에서는 여러 SLEEP 값을 더할 수 있습니다.' },
  'barrow:collapsed-entrance': { title: '무너진 입구', summary: '기운 나는 차: 카드를 뽑아 진척도를 쌓습니다. 이 고분의 타이머는 0부터 증가하며 15·30·50에 보상이 있습니다.' },
  'barrow:bellies-of-many': { title: '많은 배를 채우기', summary: '조용한 식사 대접: 타이머 12. JOY 2, STOMACH 2 두 번, NERVES 2, SENSES 3, MOOD 2를 해결합니다.' },
  'barrow:inside-job': { title: '내부의 의뢰', summary: '수상한 혼합물: SLEEP 4·FOUL 8을 준비합니다. 채집 시 타이머가 1 증가하며 일반 타이머 증감 효과는 무시합니다.' },
  'barrow:potent-poison': { title: '강력한 독', summary: '타이머 4 안에 지정된 독성 부위를 모읍니다. 판정 카드에 모은 부위마다 2를 더해 9 이상이면 성공합니다.' },
  'barrow:pilfer-unnoticed': { title: '들키지 않고 훔치기', summary: '카드 합계 21을 넘지 않도록 더 훔칠지 멈출지 고릅니다. 정확히 21이면 가장 큰 보상을 받습니다.' },
  'barrow:building-trust': { title: '신뢰 쌓기', summary: '동맹의 힘: 보통 질환의 환자를 치료합니다. 성공하면 지불금 대신 길드 명예를 얻고 고분은 정착지가 됩니다.' },
  'barrow:suitable-furnishings': { title: '알맞은 가구', summary: '집을 보금자리로: 카드 다섯 장이 정한 기본 희귀도의 재료를 순서대로 준비합니다. 걸린 시도 수에 따라 보상과 날짜가 달라집니다.' }
};
